apiVersion: v2
appVersion: auto
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 6.4.3
deprecated: false
description: paperless-ng
home: https://github.com/SelfHostedJawn/apps/tree/master/charts/incubator/paperless-ng
icon: https://raw.githubusercontent.com/the-paperless-project/paperless/master/src/paperless/static/paperless/img/logo-dark.png
keywords:
- paperless
kubeVersion: '>=1.16.0-0'
name: paperless
sources:
- https://github.com/jonaswinkler/paperless-ng
type: application
version: 1.0.0
